### ISSUE TITLE
Email notifications for CI

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust-semverver#101]
The project currently does not build on nightly.

Would it be possible to send email notifications automatically when this happens ? (e.g. via a travis-ci cron job?)

**Comment by ibabushkin** [comment]
Since I still don't have permissions to do anything to the travis setup, I fear I cannot do much about that second point (though that'd be useful). I'll set up a cron job locally and fix the build though. Sorry for your inconvenience.

**Comment by ibabushkin** [comment]
The build is fixed. Core issue remains :/

**Comment by gnzlbg** [comment]
@manisheart cc

**Comment by gnzlbg** [comment]
@manishearth cc

**Comment by gnzlbg** [comment]
and thank you for the quick fix!

**Comment by Manishearth** [comment]
@ibabushkin already has admin access to this repo

**Comment by Manishearth** [comment]
It looks like there already is a cron job

**Comment by Manishearth** [comment]
Ah, fixed the permissions. But there's no email setting there, you can add an `email` key to the .travis.yml so that you get updates, though.

**Comment by ibabushkin** [comment]
I suppose I could add "ping @gnzlbg" to my breakage fixing routine. I'll check to see if I can indeed properly adjust travis now.

**Comment by ibabushkin** [comment]
It also does not seem like I can access any settings regarding this repo on travis-ci.org. Weird.

**Comment by Manishearth** [comment]
You may need to go to your settings and sync repos

**Comment by ibabushkin** [comment]
I already did that -- on GitHub, travis is shown as having access to the rust-dev-tools org, but that does not show up on travis' side, even after multiple syncs. I am however not a member of the org, so I'm unsure if that is the blocker or something else.

**Comment by gnzlbg** [comment]
> Ah, fixed the permissions. But there's no email setting there, you can add an email key to the .travis.yml so that you get updates, though.

I think this is it, you need something like:

```yml
notifications:
  email:
    on_failure: always
```

to receive an email from travis on failure or something like that.

**Comment by orium** [comment]
Should this issue should be renamed to "Setup email notification for CI"?

**Comment by ibabushkin** [comment]
Alright, since we now have a working and slightly revamped test suite that can fail *meaningfully* (thanks @orium for your work) we can now also add people to the mail notification recipients. Do you still want that @gnzlbg?

**Comment by gnzlbg** [comment]
Until we have a way to ship this without breaking very often, it probably does not make sense to enable it unconditionally for libc, so I'd rather wait with the email notifications.

**Comment by Xanewok** [comment]
Our new scheduled run failed in GitHub Actions but it seems that no e-mail was sent, contrary to regular CI failures on PR pushes... Maybe it's related to https://github.community/t/no-email-notification-on-schedule-cron-job-failure/119638/4? @ralfjung did you manage to get it to work somehow?

**Comment by RalfJung** [comment]
> @RalfJung did you manage to get it to work somehow?

Nope, so far I haven't seen any solution better than the (rather disappointing) "set up your own SMTP client and send email manually".

**Comment by JohnTitor** [comment]
I think this is superseded by #299
