### ISSUE TITLE
Build fails with recent nightly

### ISSUE THREAD

**Issue by jrobsonchase** [rust-lang/rust-semverver#114]
It looks like a recent nightly has renamed the internal `syntax` crate to `rustc_ast`, and the `syntax_pos` crate seems gone as well, though I've yet to find where it went.

Edit: Ah, `syntax_pos` is now `rustc_span`

Edit 2: Doesn't seem like a simple find/replace, other stuff has changed in rustc as well :disappointed: It might be nice to pin the toolchain to the last nightly that can be used to build.

**Comment by ibabushkin** [comment]
I am aware of the breakage but currently unable to work on this, sorry.
I will get back to fixing everything in roughly two weeks, please hold on :)

**Comment by elichai** [comment]
The right think to do is to pin a specific nightly, and then bump that once in a while

**Comment by jrmuizel** [comment]
Yeah, pinning to a specific nightly would be very helpful

**Comment by jhpratt** [comment]
What is a nightly that is known to work?

**Comment by elichai** [comment]
> What is a nightly that is known to work?

https://github.com/rust-dev-tools/rust-semverver/pull/131
