### ISSUE TITLE
Who should review new PRs?

### ISSUE THREAD

**Issue by Xanewok** [rust-lang/rust-semverver#137]
In an effort to streamline reviewing, this repository was moved to the [rust-lang](https://github.com/rust-lang) organization (from legacy the rust-dev-tools one) in order to use the **`@bors`** bot (similar to other repos under rust-lang org). While this should be now [complete](https://github.com/rust-lang/homu/pull/116), there remains a question who should be reviewing the PRs :sweat_smile: 

@Manishearth has helped me as an interim reviewer but we discussed on Discord that it'd be good to establish others instead as reviewers.

@ibabushkin @gnzlbg @JohnTitor do you have time and would like to review any new PRs? If not, do you have an idea who could?

Disclaimer: I'm trying to integrate semverver into https://github.com/paritytech/cargo-unleash for automatic workspace package publishing, hence why I'm interested in refreshing semverver a bit :slightly_smiling_face:

**Comment by JohnTitor** [comment]
I'm happy to help maintain since libc CI also uses this crate and I'm also interested in the updates :)

**Comment by Manishearth** [comment]
@Xanewok i'm happy for you and ilya to be reviewing, and y'all can choose additional reviewers if you'd like.

**Comment by Xanewok** [comment]
@JohnTitor you should now have bors review permissions as per https://github.com/rust-lang/team/pull/486 :slightly_smiling_face:

**Comment by JohnTitor** [comment]
@Xanewok Thanks! Feel free to r? or ping me if a review is needed :)

**Comment by JohnTitor** [comment]
Semi-related to this: It'd be great if the reviewers also have permission on the repo. I currently cannot edit/close PRs/issues like https://github.com/rust-lang/rust-semverver/pull/177 :(

**Comment by Xanewok** [comment]
@pietroalbini is it possible to do this via rust-lang/team?

**Comment by Manishearth** [comment]
@Xanewok has admin rights on the repo and can add others for edit/triage access, fwiw

**Comment by Xanewok** [comment]
Oh righ,t thanks. @JohnTitor can you see if you have access to triage features?

**Comment by JohnTitor** [comment]
@Xanewok Yep, thanks!

**Comment by JohnTitor** [comment]
Currently, reviewing is done by me and sometimes @Xanewok, closing.
