### ISSUE TITLE
This crate is impossible to install

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-semverver#171]
I love the idea of this tool and would like to use it, but I just can't compile it. Every time I try (and I've tried several times over many months), I get a torrent of compilation errors.

Contrary to instructions in the readme, it doesn't seem to be compatible with just any Rust nightly. I've even tried using the exact nightly specified in the `rust-toolchain` file, but that seems to be out of sync with the source too:

```
error[E0432]: unresolved import `rustc_middle::ty::BoundRegion`
   --> src/translate.rs:324:31
    |
324 |         use rustc_middle::ty::BoundRegion::BrNamed;
    |                               ^^^^^^^^^^^ `BoundRegion` is a struct, not a module
```

Given how fragile is its compatibility with rustc, maybe you could provide precompiled binary releases instead?

**Comment by JohnTitor** [comment]
Are you using `cargo +nightly-2020-11-19 install --git https://github.com/rust-dev-tools/rust-semverver`? It works on my end (yeah, it's a bit different from the instructions on README though).

**Comment by kornelski** [comment]
```text
error[E0463]: can't find crate for `rustc_hir`
  --> src/lib.rs:10:1
   |
10 | extern crate rustc_hir;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

```

**Comment by JohnTitor** [comment]
Make sure that you have `rustc-dev` and `llvm-tools-preview` components.

**Comment by kornelski** [comment]
I've had them, but apparently adding them in general didn't add them to this specific nightly.

After re-adding them it now builds!

**Comment by JohnTitor** [comment]
Glad to hear that :) I understand that the current README is confusing a bit so I'll update it later.
