### ISSUE TITLE
Re-enable dependabot

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust-semverver#85]
@rust-dev-tools this repository was moved here recently, but travis-ci, appveyor, and dependa-bot were disabled as part of the move. These need to be re-enabled.

This will need updating the links in the readme to the appropriate places (i've updated most links in #84 but idk what to do about appveyor until the service is back up).

**Comment by ibabushkin** [comment]
Appveyor should be fixed, and I've requested that Travis gets the correct permissions to work properly. I'm not sure what to do about dependabot currently.

**Comment by Xanewok** [comment]
Done in https://github.com/rust-lang/rust-semverver/commit/746822ce6ec2091a459838b137e7f5030efa3c7e
